server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/planpulse_db

security:
  oauth2:
    client:
      registration:
        google:
          client-id:
          client-secret:
          scope:
          redirect-uri:

kafka:
  bootstrap-servers: localhost:9092

sendgrid:
  api-key: ${SENDGRID_API_KEY}

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    root: INFO
    com.project.planpulse: DEBUG