server:
  port: 8080

spring:
  application:
    name: PlanPulse
  data:
    mongodb:
      uri: mongodb+srv://temp:temppassword@cluster0.o3udu.mongodb.net/planpulse_db
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: planpulse.no.reply@gmail.com
    password: oppb vloc nytm kszd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmdWxsc3RhY2stcHJvamVjdCIsIm5hbWUiOiJQbGFuUHVsc2UiLCJpYXQiOjE2MTYyMzkwMjJ9.Aks1d25iN1yQN1AnPgS68P1QbvFBTfV5oU5h2Alz1I8 # secret key for signing JWT tokens
  expiration: 86400      # token expiration in seconds (24 hours)

logging:
  level:
    root: INFO
    com.project.planpulse: DEBUG

app:
  reset-password-url: http://localhost:5001/reset-password?token= # frontend URL for password reset link
  frontend-url: https://planpulse.com

security:
  headers:
    frame-options: DENY # protect against clickjacking
    content-security-policy: "default-src 'self'; script-src 'self'" # Basic CSP for added security

